# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: narahub123
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: photo-optimizer-students09
# "service" is the name of this project. This will also be added to your AWS resource names.
service: photo-optimzier-students09

provider:
  name: aws
  runtime: nodejs20.x

functions:
  hello:
    handler: handler.hello
