# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: narahub123
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: aws-node
# "service" is the name of this project. This will also be added to your AWS resource names.
service: aws-node-students09

provider:
  name: aws
  region: ap-northeast-2
  deploymentBucket:
    name: tmd-genai1-students09
    blockPublicAccess: true
    serverSideEncryption: AES256

functions:
  hello:
    handler: handler.hello
    events:
      - httpApi:
          path: /
          method: get
